Additional documentation
pendulum-project/statime pull request #129
Opened 2023-05-22 10:59 UTC by davidv1992

Also does some minor hiding of functionality in the libraries interface to limit the surface area we need to document.

2023-05-30 12:46 UTC, Tortoaster requested changes

2023-05-30 12:46 UTC, Tortoaster commented on statime/src/network.rs
> +/// Network ports are obtained by the PTP stack from the [NetworkRuntime]. They
```suggestion
/// Network ports are obtained by the PTP stack from the [`NetworkRuntime`]. They
```

2023-05-30 12:46 UTC, Tortoaster commented on statime/src/ptp_instance.rs
> +/// ```ignore
Same idea as above. Especially because this code is used in multiple places, static analysis to verify documentation examples are up-to-date would be useful.

2023-06-01 09:05 UTC, davidv1992 commented on statime/src/lib.rs
> +//! ```
Let's delay this until the big refactor.

2023-06-01 09:05 UTC, davidv1992 commented on statime/src/ptp_instance.rs
> +/// ```ignore
Let's delay this until the big refactor.

2023-06-01 09:13 UTC, Tortoaster approved these changes

2023-06-01 09:13 UTC, merged