Refactor raw  linux clock & timex
pendulum-project/statime pull request #162
Opened 2023-07-03 13:25 UTC by folkertdev

Preparation for extracting clock functionality into a separate crate.

2023-07-03 13:29 UTC, folkertdev commented on statime-linux/src/clock/raw.rs
> +        let current_ppm = (timex.freq >> 16) as f64 + ((timex.freq & 0xffff) as f64 / 65536.0);
I had to make some adjustments to the arithmetic. I have a fuzzer verifying that my new implementation matches the old one, but nonetheless this requires careful review.

2023-07-03 13:30 UTC, folkertdev commented on statime-linux/src/clock/raw.rs
> -                & !StatusFlags::PPSTIME,
we are "unsetting" bits here, but the timex is new and therefore all zeros. So all status flags except FREQHOLD never had any effect ...

2023-07-03 13:32 UTC, folkertdev commented on statime-linux/src/clock/raw.rs
> +        timex.freq = frequency.clamp(-32_768_000 + 1, 32_768_000 - 1);
this clamping was performed in `Timex` before, but considered the range to be inclusive. Based on the linux documentation, the range is exclusive on both sides. (the particular value seems a bit random to me, but what do I know)

2023-07-03 13:32 UTC, folkertdev commented on statime-linux/src/clock/raw.rs
> +        let frequency = (ppm * 65536e6).round() as libc::c_long;
rounding here makes our logic equivalent to what `Fixed::to_bits` did. I don't think it matters too much in practice

2023-07-03 13:33 UTC, folkertdev commented on statime-linux/src/clock/raw.rs
> +        } else if leap_59 {
this assumes that we never have a forward and backward leapsecond at the same time (or close together). Seems like a fair assumption to me.

2023-07-05 08:20 UTC, davidv1992 requested changes
Mostly looks sensible to me, one small but important simplification in some of the math, but other than that seems ok. Does need lab testing before merge.

2023-07-05 08:20 UTC, davidv1992 commented on statime-linux/src/clock/raw.rs
> +        let current_ppm = (timex.freq >> 16) as f64 + ((timex.freq & 0xffff) as f64 / 65536.0);
This can be simplified:
```suggestion
        let current_ppm = timex.freq as f64 / 65536.0;
```

2023-07-05 13:13 UTC, folkertdev commented
before doing lab testing, i think we should look at what this function does

```rust
    fn adjust_offset(&mut self, time_offset: f64) -> Result<(), Error> {
        let mut timex = EMPTY_TIMEX;

        // set set an offset, it is in nanoseconds
        timex.modes = libc::ADJ_OFFSET | libc::ADJ_NANO;

        // Start with a seconds value of 0 and express the full time offset in nanos
        timex.time.tv_sec = time_offset as _;
        timex.time.tv_usec = (time_offset.fract() * 1_000_000_000.0) as _;

        // The nanos must not be negative. In that case the timestamp must be delivered
        // as a negative seconds with a postive nanos value
        while timex.time.tv_usec < 0 {
            timex.time.tv_sec -= 1;
            timex.time.tv_usec += 1_000_000_000;
        }

        self.adjtime(&mut timex)
    }
```

here `libc::ADJ_OFFSET` is used. However:

> ADJ_OFFSET
>       Set time offset from buf.offset.  Since Linux 2.6.26, the
>       supplied value is clamped to the range (-0.5s, +0.5s).  In
>       older kernels, an EINVAL error occurs if the supplied
>       value is out of range.

so `ADJ_OFFSET` uses the value from the `timex.offset` field. But we never set this field in our timex: we set the timex.time field. So I suspect that this function does not work and that `libc::ADJ_SETOFFSET` should be used instead

>        ADJ_SETOFFSET (since Linux 2.6.39)
>               Add buf.time to the current time.  If buf.status includes
>               the ADJ_NANO flag, then buf.time.tv_usec is interpreted as
>               a nanosecond value; otherwise it is interpreted as
>               microseconds.
> 
>               The value of buf.time is the sum of its two fields, but
>               the field buf.time.tv_usec must always be nonnegative.
>               The following example shows how to normalize a timeval
>               with nanosecond resolution.
> 
>                   while (buf.time.tv_usec < 0) {
>                       buf.time.tv_sec  -= 1;
>                       buf.time.tv_usec += 1000000000;
>                   }

2023-07-07 06:43 UTC, davidv1992 approved these changes

2023-07-07 06:44 UTC, merged