use an independent timer for delay requests
pendulum-project/statime pull request #208
Opened 2023-07-27 14:18 UTC by folkertdev

2023-07-27 14:29 UTC, folkertdev commented
one thing I'm not 100% sure about is whether we do this

> a) The initial Delay_Req message may be transmitted when required.

this is pretty vague. when is it required?

2023-07-28 18:21 UTC, davidv1992 approved these changes

2023-07-28 18:25 UTC, davidv1992 requested changes
Apologies for the double review, missed a bug the first time round. This mostly looks good, however we should reset the delay request timer upon entering the slave state otherwise it might never fire.

2023-07-28 18:25 UTC, davidv1992 commented
> one thing I'm not 100% sure about is whether we do this
> 
> > a) The initial Delay_Req message may be transmitted when required.
> 
> this is pretty vague. when is it required?

I think (but this is just my interpretation) this means that we are allowed to just immediately do a delay request whenever we need to know our delay but don't have any information on it yet.

More practically, I think we can interpret this as permission to do a delay request immediately upon switching to the slave state.

2023-08-03 09:09 UTC, davidv1992 approved these changes

2023-08-03 09:09 UTC, merged