Fix for not being able to adjust clock backwards.
pendulum-project/statime pull request #222
Opened 2023-08-10 13:42 UTC by davidv1992

2023-08-10 13:55 UTC, folkertdev requested changes

2023-08-10 13:55 UTC, folkertdev commented on statime-linux/src/clock/mod.rs
> +        };
I'd like more in terms of documentation here. Also it might be clearer to do the arithmetic on the integer representation rather than `f64`.

2023-08-16 07:03 UTC, davidv1992 commented on statime-linux/src/clock/mod.rs
> +        };
Changed this, please let me know what you think of the new approach.

2023-08-16 08:26 UTC, folkertdev commented on statime-linux/src/clock/mod.rs
> +        let offset_nanos: i128 = time_offset.nanos().lossy_into();
can we push the combination of `.nanos.lossy_into()` in to a helper function in statime itself? Then we don't need a dependency on fixed here.

2023-08-16 08:35 UTC, davidv1992 commented on statime-linux/src/clock/mod.rs
> +        let offset_nanos: i128 = time_offset.nanos().lossy_into();
Done

2023-08-16 08:38 UTC, folkertdev approved these changes

2023-08-16 08:38 UTC, merged