Getting started guide for statime.
pendulum-project/statime pull request #319
Opened 2023-11-16 14:35 UTC by davidv1992

2023-11-16 15:09 UTC, folkertdev commented on docs/guide/getting-started.md
> +# Installing statime
the guide uses "statime"  and not "statime-linux"? (I don't disagree with that I think, but just good clarify)

2023-11-16 15:12 UTC, folkertdev commented on docs/guide/getting-started.md
> +If the network interface support hardware timestamping for a specific ptp hardware clock, this can be enabled by specifying the hardware clock of the network interface:
text is good but I'm not sure this should be part of "getting started". Could just be a link to a page/section on hardware timestamping in the future.

2023-11-16 15:14 UTC, folkertdev commented on docs/guide/getting-started.md
> +network_mode = "ethernet"
no kebab case yet, and we won' t change that before the release?

2023-11-16 15:16 UTC, folkertdev commented on docs/guide/getting-started.md
> +```toml
I think having the snippet be 

```toml
[[port]]
interface = "<interface name>"
network_mode = "ipv4" // or "ipv6" or "ethernet"
``` 

saves a bunch of text/vertical space here. details of ipv6/ethernet feel a bit out of place for a getting started guide.

2023-11-23 14:06 UTC, davidv1992 commented on docs/guide/getting-started.md
> +If the network interface support hardware timestamping for a specific ptp hardware clock, this can be enabled by specifying the hardware clock of the network interface:
Given that pretty much the only reason for ptp is to get higher precision, I think we should keep this in the getting started guide as people will expect hardware timestamping to work pretty quickly

2023-11-24 08:55 UTC, davidv1992 commented on docs/guide/getting-started.md
> +# Installing statime
Yes, that is now also the binary name

2023-11-24 13:33 UTC, cikzh requested changes

2023-11-24 13:33 UTC, cikzh commented on docs/guide/getting-started.md
> +If the network interface support hardware timestamping for a specific ptp hardware clock, this can be enabled by specifying the hardware clock of the network interface:
```suggestion
If the network interface supports hardware timestamping for a specific PTP hardware clock, this can be enabled by specifying the hardware clock of the network interface:
```

2023-11-24 13:33 UTC, cikzh commented on docs/guide/getting-started.md
> +Statime will then enable hardware timestamping, and automatically synchronize the hardware clock and the system clock as needed. To determine which hardware clock belongs to an interface, ethtool can
```suggestion
Statime will then enable hardware timestamping, and automatically synchronize the hardware clock and the system clock as needed. To determine which hardware clock belongs to an interface, `ethtool` can be used:
```

2023-11-24 13:33 UTC, cikzh commented on docs/guide/getting-started.md
> +We can now start the statime deamon through systemd with
```suggestion
We can now start the statime daemon through systemd with
```

2023-11-24 13:33 UTC, cikzh commented on docs/guide/getting-started.md
> +If everything is configured well, and there is a ptp time source available in your network, the status of the demon should look something like
```suggestion
If everything is configured well, and there is a PTP time source available in your network, the status of the daemon should look something like:
```

2023-11-24 13:37 UTC, cikzh commented on docs/guide/getting-started.md
> +If the network interface support hardware timestamping for a specific ptp hardware clock, this can be enabled by specifying the hardware clock of the network interface:
I agree that we should keep this in. Users ending up here while looking for a way to use their new Raspberry Pi 5 will benefit from this.

2023-11-24 14:18 UTC, cikzh approved these changes

2023-11-24 14:18 UTC, merged