Observability in library and statime linux
pendulum-project/statime pull request #390
Opened 2024-01-31 16:45 UTC by cikzh

This PR will add a Prometheus exporter, which will get its metrics from statime-linux via a Unix Domain Socket, very similar to how ntpd-rs does it.

2024-02-08 20:12 UTC, rnijveld requested changes

2024-02-08 20:12 UTC, rnijveld commented on statime/src/ptp_instance.rs
> +        self.state.borrow().default_ds.into()
DefaultDS is copied here implicitly and then copied once more with the into (I'm not sure why DefaultDS and CurrentDS implement clone, seems like a papercut).

2024-02-08 20:12 UTC, rnijveld commented on statime/src/ptp_instance.rs
> +        self.state.borrow().parent_ds.clone().into()
This clone could then be removed.

2024-02-08 20:12 UTC, rnijveld commented on statime/src/ptp_instance.rs
> +        self.state.borrow().time_properties_ds.into()
Same for this one.

2024-02-14 07:58 UTC, davidv1992 approved these changes
Note: Reverts #405 but I am fine with that as that did not fix the issue anyway.

2024-02-14 08:00 UTC, davidv1992 requested changes
Apologies, missed that sdoId still has the default serde deserializer, which is problematic as an sdo id should be below 2^12, which this doesn't enforce.

2024-02-16 11:10 UTC, davidv1992 approved these changes

2024-02-16 11:13 UTC, davidv1992 commented on statime/src/datastructures/datasets/time_properties.rs
>  #[derive(Default, Copy, Clone, Debug, Eq, PartialEq)]
I disagree, this is small plain old data, so I think it should be copy.

2024-02-21 08:08 UTC, rnijveld approved these changes

2024-02-21 08:11 UTC, merged