Metric formatting
pendulum-project/statime pull request #417
Opened 2024-02-22 16:02 UTC by cikzh

Adds Prometheus formatting for most dataset members. Builds on #390

2024-02-29 13:57 UTC, cikzh commented
@davidv1992 I've pulled the formatting code into it's own file, since it was getting quite long. While reviewing, please pay attention to the correctness of the descriptions given in the `format_metric` calls.

2024-03-01 08:38 UTC, davidv1992 commented on statime-linux/src/metrics/exporter.rs
> +use statime::observability::ObservableInstanceState;
As discussed in person, can you remove this struct and associated functions from statime.

2024-03-01 09:18 UTC, davidv1992 requested changes
Some minor things around commenting out lines instead of outright removing em.

2024-03-01 09:18 UTC, davidv1992 commented on statime/src/datastructures/datasets/parent.rs
> +    //pub(crate) observed_parent_clock_phase_change_rate: u32,
Why not just remove this

2024-03-01 09:18 UTC, davidv1992 commented on statime/src/datastructures/datasets/parent.rs
> +            //observed_parent_clock_phase_change_rate: 0x7fffffff,
Why not just remove this

2024-03-01 09:18 UTC, davidv1992 commented on statime/src/observability/current.rs
> +    // pub mean_delay: i128,
Why not just remove this.

2024-03-01 09:18 UTC, davidv1992 commented on statime/src/observability/current.rs
> +            // mean_delay: v.mean_delay.nanos_rounded(),
Why not just remove this.

2024-03-01 09:18 UTC, davidv1992 commented on statime/src/observability/parent.rs
> +    // pub observed_parent_clock_phase_change_rate: u32,
why not just remove this?

2024-03-01 09:18 UTC, davidv1992 commented on statime/src/observability/parent.rs
> +            // observed_parent_clock_phase_change_rate: v.observed_parent_clock_phase_change_rate,
Why not just remove this

2024-03-01 10:09 UTC, davidv1992 approved these changes

2024-03-01 10:10 UTC, merged