Draft: Ptp master
pendulum-project/statime pull request #46
Opened 2023-01-17 10:24 UTC by bramtweedegolf

2023-01-17 14:09 UTC, diondokter requested changes

2023-01-17 14:09 UTC, diondokter commented on statime/src/port.rs
> +        port.tc_port.send(&follow_up_message_encode);
Non tc port

2023-01-17 14:09 UTC, diondokter commented on statime/src/port.rs
> +        if port.delay_resp_seq_id == u16::MAX {
Wrapping add

2023-01-17 14:09 UTC, diondokter commented on statime/src/port.rs
> +        port.tc_port.send(&delay_resp_encode);
Non tc port?

2023-01-17 14:09 UTC, diondokter commented on statime/src/port.rs
> +        if id == self.watch.id() {
Change the name of this watch

2023-01-17 14:09 UTC, diondokter commented on statime/src/port.rs
> +            self.send_follow_up_message(current_time);
Yes

2023-01-18 08:17 UTC, bramtweedegolf commented on statime/src/port.rs
> +                TimeSource::from_primitive(0xa0), //time_source: TimeSource,
@diondokter Maybe I missed something in the code, but it seems like we don't establish a TimeSource anywhere at the moment. It should maybe be set by the Clock implementations? I added a TODO comment.

2023-01-18 11:03 UTC, bramtweedegolf commented on statime/src/port.rs
> +                TimeSource::from_primitive(0xa0), //time_source: TimeSource,
Will implement this when the state-machine branch has been merged.

2023-01-18 11:06 UTC, bramtweedegolf commented on statime/src/port.rs
> +            self.send_follow_up_message(current_time);
Will implement after the state-machine branch has been merged.

2023-01-20 13:25 UTC, Tortoaster requested changes

2023-01-20 13:25 UTC, Tortoaster commented on statime/src/port.rs
> +                        .set_alarm(Duration::from_log_interval(announce_receipt_timeout));
`announce_receipt_timeout` is zelf geen log interval, maar het aantal keren dat `announce_interval` herhaald wordt voor een `ANNOUNCE_RECEIPT_TIMEOUT_EXPIRES` event (7.7.3.1).

2023-01-20 13:25 UTC, Tortoaster commented on statime/src/port.rs
> +                        .set_alarm(Duration::from_log_interval(announce_receipt_timeout));
^

2023-01-20 13:25 UTC, Tortoaster commented on statime/src/port.rs
> +                        .set_alarm(Duration::from_log_interval(announce_receipt_timeout));
^

2023-01-20 13:28 UTC, Tortoaster requested changes

2023-01-20 13:28 UTC, Tortoaster commented on statime/src/ptp_instance.rs
> +            config.port_config.announce_receipt_timeout,
^

2023-01-20 13:31 UTC, Tortoaster requested changes

2023-01-20 13:31 UTC, Tortoaster commented on statime/src/port.rs
> +                        self.portdata.port_config.announce_receipt_timeout,
^

2023-01-24 09:40 UTC, bramtweedegolf commented on statime/src/port.rs
> +                        .set_alarm(Duration::from_log_interval(announce_receipt_timeout));
Well spotted!

2023-03-03 09:30 UTC, closed without merging