Add path trace support
pendulum-project/statime pull request #482
Opened 2024-07-01 12:57 UTC by Florob

This adds support for path trace option as described in section 16.2 of IEEE Std1588-2019.

The main purpose of this is loop detection. I've also found it rather useful for general debugging as it makes the path Announces take through the network visible. It is also a prerequisite for potential IEEE Std 802.1as (gPTP) support where this option is mandatory.

2024-07-10 07:24 UTC, davidv1992 approved these changes
Looks good to me, one minor thing I don't feel comfortable signing off myself.

2024-07-10 07:24 UTC, davidv1992 commented on statime-linux/src/metrics/format.rs
> +
@rnijveld This looks ok to me, but I am not that familiar with prometheus. Is this a reasonable approach to exposing the data?

2024-07-10 07:44 UTC, rnijveld commented on statime-linux/src/metrics/format.rs
> +
I'm afraid this isn't right, a measurement should always be a numeric value, strings aren't supported. Unfortunately there is no way in Rust to limit a generic T to only numeric types, so the Measurement struct supports any type, which is why this compiles, but it will generate invalid prometheus output. I'm not sure how to best handle a path trace through prometheus metrics. One thing we could do is have `path_trace_list[steps_removed=x,clock_identity=y] = x` (i.e. repeating the steps_removed as both a label and as the value), but it would be a little bit of a stretch of the data format.

2024-07-10 07:47 UTC, rnijveld requested changes
We need to find an alternative way to format the prometheus metrics, see my other comment.

2024-07-10 11:17 UTC, Florob commented on statime-linux/src/metrics/format.rs
> +
It would have been helpful to know that these are supposed to be prometheus metrics, which is not mentioned anywhere in the code base AFAICT. I suppose it's also a valid question whether this should be exposed as a *metric* at all. However, I do also think that is something that generally should be exposed by a PTP daemon.

I suppose a clock identity is technically a 64-bit integer, so we could pass it as such. It's just not exactly readable.

2024-07-10 11:32 UTC, Florob commented on statime-linux/src/metrics/format.rs
> +
Reading up on Prometheus a bit more it seems like values are supposed to be float64.
So `Into<f64>` would probably be an appropriate bound, and `u64` obviously won't fit.

2024-08-23 09:27 UTC, davidv1992 commented
Merged via #525

2024-08-23 09:27 UTC, closed without merging