RFC: virtual (overlay) system clock
pendulum-project/statime pull request #504
Opened 2024-08-01 21:14 UTC by teowoz

As discussed in #389

This adds configuration option `virtual-system-clock` which is disabled by default which means that OS clock will be used directly as it always was.

If set to true, OS clock will be read-only. Overlay clock will be based on it and used for synchronization.

Tested with Dante device, both master and slave. Seems to work. Hardware timestamping not tested yet due to #503 and https://github.com/pendulum-project/timestamped-socket/issues/66

Exporting the clock to other processes using [usrvclock local protocol (currently draft)](https://gitlab.com/lumifaza/usrvclock) is planned.

2024-08-14 22:46 UTC, teodly commented
Added ability to export clock to other apps using [usrvclock](https://gitlab.com/lumifaza/usrvclock) protocol. Not tested yet - currently I don't have access to PTP hardware, will test in 2 weeks.

2024-08-22 08:24 UTC, davidv1992 commented
Thank you for the contribution. This is looking interesting, however I have a few concerns. First, I would like to ask you to split the usrvclock stuff into it's own PR. It needs additional consideration due to the extra dependencies and the fact that it is not yet a widely accepted standard, and splitting it would make adoption of the rest of the changes here easier. Also, #517 might be better for the current use cases for this.

Beyond that, having had a short look at the changes, the rest looks decent. There are a few formatting issues and some commented out code that should be fixed before this is ready for merging, and I would like to ask you to reconsider the auto_impls dependency. We are looking to reduce the number of dependencies as we progress to version 1.0, and this would go against that goal.

But again, other than those minor things, this is some nice work that we would be interested in.

2024-08-22 08:25 UTC, davidv1992 requested changes
See above comment

2024-08-30 07:47 UTC, davidv1992 requested changes
Few minor things that still need improving, but definitely on the right track I think.

2024-08-30 07:47 UTC, davidv1992 commented on statime/src/overlay_clock.rs
> +    }
This won't work if self.freq_scale_ppm_diff is not zero, as we change the last sync time, and the shift is not update to match that change.

2024-08-30 07:47 UTC, davidv1992 commented on statime-linux/src/main.rs
> +        let (port_clock, port_clock2, timestamping) = match port_config.hardware_clock {
Why are the two clock variables needed here? Can't we get away with one? looking at the code below they essentially always are the same clock.

2024-08-30 07:47 UTC, davidv1992 commented on statime-linux/src/main.rs
> +//type SharedBoxedClock = SharedClock<BoxedClock>;
Please remove this line

2024-08-30 07:47 UTC, davidv1992 commented on statime-linux/src/clock/mod.rs
> +}
This essentially replaces `timestamp_to_time`, but I am missing the change that removes that function

2024-08-30 09:32 UTC, teodly commented on statime-linux/src/main.rs
> +        let (port_clock, port_clock2, timestamping) = match port_config.hardware_clock {
Because we need separate owned `impl Clock` instances: for `instance.add_port` and `port_task`. Originally `port_clock.clone()` was used for this but we can't clone a `Box`. So we need to clone before boxing.

2024-08-30 09:38 UTC, teodly commented on statime/src/overlay_clock.rs
> +    }
You're right, `offset` is in overlay timescale, not underlying.

2024-08-30 12:44 UTC, davidv1992 commented on statime-linux/src/main.rs
> +        let (port_clock, port_clock2, timestamping) = match port_config.hardware_clock {
boxes can be cloned assuming the inner thing is clone, which we can guarantee here I think, so I would strongly prefer that approach

2024-08-30 23:59 UTC, teodly commented on statime-linux/src/main.rs
> +        let (port_clock, port_clock2, timestamping) = match port_config.hardware_clock {
Done, but it required a bit of boilerplate code: https://stackoverflow.com/questions/30353462/how-to-clone-a-struct-storing-a-boxed-trait-object

2024-09-19 14:06 UTC, davidv1992 commented
Can you fix the failing style check?

2024-09-20 13:56 UTC, davidv1992 approved these changes

2024-09-20 13:59 UTC, merged